In [13]:
print("Numpy Second Day")

Numpy Second Day


In [14]:
import numpy as np

In [15]:
One_dim = np.array([46,63,23])
One_dim 

array([46, 63, 23])

In [16]:
print(One_dim[0])
print(One_dim[1])
print(One_dim[2])
print(One_dim[0:2])


46
63
23
[46 63]


In [17]:
two_dim = np.array([[46,63,23],[4,5,6],[7,8,9]])
print(two_dim)
print(two_dim[0])
print(two_dim[0][1])
print(two_dim[1])
print(two_dim[1,2])
print(two_dim[1,:2])
print(two_dim[2,1:])
print("-"*50)
print(two_dim[0:2]) # 0,1,
print(two_dim[0:2][1:])

[[46 63 23]
 [ 4  5  6]
 [ 7  8  9]]
[46 63 23]
63
[4 5 6]
6
[4 5]
[8 9]
--------------------------------------------------
[[46 63 23]
 [ 4  5  6]]
[[4 5 6]]


In [18]:
three_array = np.array([[[3,4,5],[6,7,8]],
                        [[11,22,33],[55,66,77]],
                        [[16,85,34],[5,6,77]]])
print(three_array)
print(three_array.shape)

[[[ 3  4  5]
  [ 6  7  8]]

 [[11 22 33]
  [55 66 77]]

 [[16 85 34]
  [ 5  6 77]]]
(3, 2, 3)


In [19]:
print(three_array[0])
print(three_array[0,1])
print(three_array[0,1,1])
print(three_array[2])
print(three_array[2,1])
print(three_array[2,1,-2])
print(three_array[1:])
print(three_array[1:][1:])
print("--"*50)
print(three_array[1:][1:][0])
print(three_array[1:][1:][0][0])
print(three_array[1:][1:][0][0][1:])

[[3 4 5]
 [6 7 8]]
[6 7 8]
7
[[16 85 34]
 [ 5  6 77]]
[ 5  6 77]
6
[[[11 22 33]
  [55 66 77]]

 [[16 85 34]
  [ 5  6 77]]]
[[[16 85 34]
  [ 5  6 77]]]
----------------------------------------------------------------------------------------------------
[[16 85 34]
 [ 5  6 77]]
[16 85 34]
[85 34]


In [20]:
One_dim = np.array([46,63,23])
One_dim 

array([46, 63, 23])

In [21]:

One_dim[1] = 55

In [22]:
print(One_dim)

[46 55 23]


In [23]:
One_dim = np.array([46,63,23])
print(One_dim) 
del One_dim

[46 63 23]


In [24]:
One_dim

NameError: name 'One_dim' is not defined

In [ ]:
One_dim[0] = 100
One_dim

array([100,  55,  23])

In [ ]:
One_dim[0:] = [90,80,70]
One_dim

array([90, 80, 70])

In [ ]:
two_dim = np.array([[46,63,23],[4,5,6],[7,8,np.nan]])
print(two_dim)

[[46. 63. 23.]
 [ 4.  5.  6.]
 [ 7.  8. nan]]


In [ ]:
two_dim = np.array([[46,63,23],[4,5,6],[7,8,9]])
print(two_dim)
two_dim[0][1] = 78
two_dim

[[46 63 23]
 [ 4  5  6]
 [ 7  8  9]]


array([[46, 78, 23],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
two_dim[-1][-1] = 10
two_dim

array([[46, 78, 23],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [ ]:
two_dim[-1][1:] = [18,20]
(two_dim)
print()

In [ ]:
print(two_dim)
print(two_dim[two_dim>10])
print(two_dim[two_dim<10])
print(two_dim[two_dim%2==0])
print(two_dim[two_dim%2==1])

[[46 78 23]
 [ 4  5  6]
 [ 7 18 20]]
[46 78 23 18 20]
[4 5 6 7]
[46 78  4  6 18 20]
[23  5  7]


In [ ]:
a = 345
b = 343

print(a)
print(b)

345
343


In [ ]:
three_array = np.array([[[3,4,5],[6,7,8]],
                        [[11,22,33],[55,66,77]],
                        [[16,85,34],[5,6,77]]])
print(three_array)
print(three_array[0])
print(three_array[0][1])
print(three_array[0][1][0])
three_array[0][1][0] = 60
print(three_array)

[[[ 3  4  5]
  [ 6  7  8]]

 [[11 22 33]
  [55 66 77]]

 [[16 85 34]
  [ 5  6 77]]]
[[3 4 5]
 [6 7 8]]
[6 7 8]
6
[[[ 3  4  5]
  [60  7  8]]

 [[11 22 33]
  [55 66 77]]

 [[16 85 34]
  [ 5  6 77]]]


In [ ]:
two_dim = np.array([[46,63,23],[4,5,6],[7,8,9]])
two_dim

array([[46, 63, 23],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
print(two_dim.min())

4


In [ ]:
print(two_dim.max())

63


In [ ]:
print(two_dim.mean())
print(np.mean(two_dim))

19.0
19.0


In [ ]:
np.median(two_dim)

np.float64(8.0)

In [ ]:
np.std(two_dim)

np.float64(20.09975124224178)

In [ ]:
np.var(two_dim)

np.float64(404.0)

In [ ]:
arr = np.array([3,4,5,6,7,8])
print(arr.min())
print(arr.argmin())

3
0


In [ ]:
arr = np.array([3,4,5,6,7,8,1])
print(arr.min())
print(arr.argmin())

1
6


In [ ]:
arr = np.array([[3,4,5,6],[7,8,1,7]])
print(arr)
print(arr.min())
print(arr.argmin(axis=0)) # column
print(arr.argmin(axis=1))

[[3 4 5 6]
 [7 8 1 7]]
1
[0 0 1 0]
[0 2]


In [39]:
arr = np.array([[3,4,5,6],[7,8,1,7]])
print(arr)
print(arr.max())
print(np.argmax(arr))
print(np.argmax(arr,axis=0)) # row vise
print(np.argmax(arr,axis=1)) # column vise

[[3 4 5 6]
 [7 8 1 7]]
8
5
[1 1 0 1]
[3 1]


In [31]:
three_array = np.array([[[30,4,5],[6,7,8]],
                        [[11,22,33],[55,66,77]],
                        [[16,85,34],[5,6,77]]])
print(three_array.min())
print(three_array)
print(np.argmin(three_array))
print(np.argmin(three_array,axis=0)) # row (vertical)
print(np.argmin(three_array,axis = 1)) # column (Horizontal)

4
[[[30  4  5]
  [ 6  7  8]]

 [[11 22 33]
  [55 66 77]]

 [[16 85 34]
  [ 5  6 77]]]
1
[[1 0 0]
 [2 2 0]]
[[1 0 0]
 [0 0 0]
 [1 1 0]]


In [29]:
three_array = np.array([[[39,4,5],[6,7,8]],
                        [[113,22,33],[595,66,77]]],)
print(three_array.min())
print(three_array)
#
print(np.argmin(three_array,axis=0)) # Row
print(np.argmin(three_array,axis=1)) # Column


4
[[[ 39   4   5]
  [  6   7   8]]

 [[113  22  33]
  [595  66  77]]]
[[0 0 0]
 [0 0 0]]
[[1 0 0]
 [0 0 0]]


# array joining

In [35]:
a = np.array([45,64,23])
b = np.array([66,88,34])

concat = np.concatenate((a,b))
print(concat)
concat_0 = np.concatenate((a,b),axis = 0)
print(concat_0)
concat_1 = np.concatenate((a,b),axis = 1)
print(concat_1)

[45 64 23 66 88 34]
[45 64 23 66 88 34]


AxisError: axis 1 is out of bounds for array of dimension 1

In [42]:
a = np.array([[45,64,23],[11,22,33]])
b = np.array([[66,88,34],[90,25,65]])
print("Array a")
print(a)
print("Array a")
print(b)
print("Vertical Joining ")
concat_0 = np.concatenate((a,b),axis = 0) # Vertical 
print(concat_0)
print("Horizontal Joining")
concat_1 = np.concatenate((a,b),axis = 1) # Horizontal
print(concat_1)


Array a
[[45 64 23]
 [11 22 33]]
Array a
[[66 88 34]
 [90 25 65]]
Vertical Joining 
[[45 64 23]
 [11 22 33]
 [66 88 34]
 [90 25 65]]
Horizontal Joining
[[45 64 23 66 88 34]
 [11 22 33 90 25 65]]


In [51]:
a = np.array([45,64,23])
b = np.array([66,88,34])
print(a)
print(b)

stack_1d = np.array((a,b))
print(stack_1d)
print(stack_1d.ndim)

[45 64 23]
[66 88 34]
[[45 64 23]
 [66 88 34]]
2


In [ ]:
a = np.array([[45,64,23],[11,22,33]])
b = np.array([[66,88,34],[90,25,65]])
print("Array a")
print(a)
print("Array a")
print(b)
print("__"*50)
stack = np.stack((a,b))
print(stack)
#print("__"*50)
# stack_0 = np.stack((a,b),axis=0)
# print(stack_0)
# print("__"*50)
# stack_1 = np.stack((a,b),axis=0)
# print(stack_1)
# stack_1.ndim

Array a
[[45 64 23]
 [11 22 33]]
Array a
[[66 88 34]
 [90 25 65]]
____________________________________________________________________________________________________
[[[45 64 23]
  [11 22 33]]

 [[66 88 34]
  [90 25 65]]]
____________________________________________________________________________________________________


In [ ]:
# Vstack
a = np.array([[45,64,23],[11,22,33]])
b = np.array([[66,88,34],[90,25,65]])
print("Array a")
print(a)
print("Array a")
print(b)
print("__"*50)
stack = np.vstack((a,b))
print(stack)

Array a
[[45 64 23]
 [11 22 33]]
Array a
[[66 88 34]
 [90 25 65]]
____________________________________________________________________________________________________
[[45 64 23]
 [11 22 33]
 [66 88 34]
 [90 25 65]]


In [ ]:
# Horizontal Stack
a = np.array([[45,64,23],[11,22,33]])
b = np.array([[66,88,34],[90,25,65]])
print("Array a")
print(a)
print("Array a")
print(b)
print("__"*50)
stack = np.hstack((a,b))
print(stack)

Array a
[[45 64 23]
 [11 22 33]]
Array a
[[66 88 34]
 [90 25 65]]
____________________________________________________________________________________________________
[[45 64 23 66 88 34]
 [11 22 33 90 25 65]]


In [59]:
z = np.array([[45, 64, 23, 66, 88, 34],[11, 22, 33, 90, 25, 65]])
print(z)

[[45 64 23 66 88 34]
 [11 22 33 90 25 65]]


In [62]:
# array Transformation
transform_z = z.T
print(transform_z)

[[45 11]
 [64 22]
 [23 33]
 [66 90]
 [88 25]
 [34 65]]


In [61]:
np.transpose(z)

array([[45, 11],
       [64, 22],
       [23, 33],
       [66, 90],
       [88, 25],
       [34, 65]])

In [74]:
z = np.array([[45, 64, 23, 66, 88, 34],[11, 22, 33, 90, 25, 65]])
print(z)
# sorting
# print("Sorting")
print("Horizontal Sorting")
zz = np.sort(z,axis=1)  
print(zz)
print("Vertical sorting")
zz = np.sort(z,axis=0) # Vertical
print(zz)

[[45 64 23 66 88 34]
 [11 22 33 90 25 65]]
Horizontal Sorting
[[23 34 45 64 66 88]
 [11 22 25 33 65 90]]
Vertical sorting
[[11 22 23 66 25 34]
 [45 64 33 90 88 65]]


In [82]:
z = np.array([[45, 64, 23, 66, 88, 34],[11, 22, 33, 90, 25, 65]])
print("Original array")
print(z)
z[0][0] = 90
print(z)

Original array
[[45 64 23 66 88 34]
 [11 22 33 90 25 65]]
[[90 64 23 66 88 34]
 [11 22 33 90 25 65]]


In [83]:
copy_z = np.copy(z)
print("Copied array")
print(copy_z)

Copied array
[[90 64 23 66 88 34]
 [11 22 33 90 25 65]]


In [84]:
copy_z[0][0] = 100
copy_z

array([[100,  64,  23,  66,  88,  34],
       [ 11,  22,  33,  90,  25,  65]])

In [85]:
z

array([[90, 64, 23, 66, 88, 34],
       [11, 22, 33, 90, 25, 65]])

In [87]:
z = np.array([[45, 64, 23, 66, 88, 34],[11, 22, 33, 90, 25, 65]])
print("Original array")
print(z)

view_z = z.view()
print("Viewd copy array")
print(view_z)

Original array
[[45 64 23 66 88 34]
 [11 22 33 90 25 65]]
Viewd copy array
[[45 64 23 66 88 34]
 [11 22 33 90 25 65]]


In [88]:
z[0,0] = 34
z

array([[34, 64, 23, 66, 88, 34],
       [11, 22, 33, 90, 25, 65]])

In [89]:
view_z

array([[34, 64, 23, 66, 88, 34],
       [11, 22, 33, 90, 25, 65]])

In [90]:
view_z[0,1] = 1000
view_z

array([[  34, 1000,   23,   66,   88,   34],
       [  11,   22,   33,   90,   25,   65]])

In [91]:
z

array([[  34, 1000,   23,   66,   88,   34],
       [  11,   22,   33,   90,   25,   65]])