In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.2.5


In [13]:
# 0 dimensional array
zero_array = np.array(58)
print(zero_array)
print(type(zero_array))
print(zero_array.ndim)
print(zero_array.size)
print(zero_array.shape)

58
<class 'numpy.ndarray'>
0
1
()


In [17]:
# 1D array

one_d_array = np.array([4,2,5,6])
print(one_d_array)
print(type(one_d_array))
print(one_d_array.ndim)
print(one_d_array.size)
print(one_d_array.shape)

[4 2 5 6]
<class 'numpy.ndarray'>
1
4
(4,)


In [22]:
# 2d Array

two_array = np.array([[3,4,5],[6,7,4]])
print(two_array)
print(two_array.ndim)
print(two_array.shape)
print(two_array.size)
print(two_array.dtype)


[[3 4 5]
 [6 7 4]]
2
(2, 3)
6
int64


In [23]:
two_array = np.array([[3.5,4,5],[6,7,4]])
print(two_array)
print(two_array.ndim)
print(two_array.shape)
print(two_array.size)
print(two_array.dtype)


[[3.5 4.  5. ]
 [6.  7.  4. ]]
2
(2, 3)
6
float64


In [24]:
two_array = np.array([[3,"4",5],[6,7,4]])
print(two_array)
print(two_array.ndim)
print(two_array.shape)
print(two_array.size)
print(two_array.dtype)


[['3' '4' '5']
 ['6' '7' '4']]
2
(2, 3)
6
<U21


In [25]:
py_arr2 = np.array([[45,23,65],[89,21]])
print(py_arr2)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [26]:
py_arr2 = np.array([[45,23,65],[89,21,90]])
print(py_arr2)

[[45 23 65]
 [89 21 90]]


In [27]:
py_arr2 = np.array([[45,23,65],[89,21,90],[89,45,65]])
print(py_arr2)

[[45 23 65]
 [89 21 90]
 [89 45 65]]


In [29]:
py_arr2 = np.array([[45,23,65,67],[99,89,21,90],[77,89,45,65]])
print(py_arr2)
print(py_arr2.shape)

[[45 23 65 67]
 [99 89 21 90]
 [77 89 45 65]]
(3, 4)


In [31]:
# 3D Array

three_arr = np.array([[[4,5,6]],[[5,7,8]]])
print(three_arr.ndim)
print(three_arr)
print(three_arr.shape)

3
[[[4 5 6]]

 [[5 7 8]]]
(2, 1, 3)


In [35]:
three_arr = np.array([[[4,5,6],[66,77,55]],[[5,7,8],[33,22,11]]])
print(three_arr.ndim)
print(three_arr)
print(three_arr.shape)

3
[[[ 4  5  6]
  [66 77 55]]

 [[ 5  7  8]
  [33 22 11]]]
(2, 2, 3)


In [36]:
three_arr = np.array([[[4,5,6],[66,77,55]],[[5,7,8],[33,22,11]],[[90,80,70],[34,35,36]]])
print(three_arr.ndim)
print(three_arr)
print(three_arr.shape)

3
[[[ 4  5  6]
  [66 77 55]]

 [[ 5  7  8]
  [33 22 11]]

 [[90 80 70]
  [34 35 36]]]
(3, 2, 3)


In [38]:
three_arr = np.array([[[4,5,6],[66,77,55],[56,57,57]],
                      [[5,7,8],[33,22,11],[4,3,56]],
                      [[90,80,70],[34,35,36],[33,44,66]]])
print(three_arr.ndim)
print(three_arr)
print(three_arr.shape)
print(three_arr.size)

3
[[[ 4  5  6]
  [66 77 55]
  [56 57 57]]

 [[ 5  7  8]
  [33 22 11]
  [ 4  3 56]]

 [[90 80 70]
  [34 35 36]
  [33 44 66]]]
(3, 3, 3)
27


In [39]:
three_arr = np.array([[[4,5,6],[66,77,55],[56,57,57]],
                      [[5,7,8],[33,22,11],[4,3,56]],
                      [[90,80,70],[34,35,36],[33,44,66]]],ndmin=5)
print(three_arr.ndim)
print(three_arr)
print(three_arr.shape)
print(three_arr.size)

5
[[[[[ 4  5  6]
    [66 77 55]
    [56 57 57]]

   [[ 5  7  8]
    [33 22 11]
    [ 4  3 56]]

   [[90 80 70]
    [34 35 36]
    [33 44 66]]]]]
(1, 1, 3, 3, 3)
27


In [40]:
three_arr = np.array([[[4,5,6],[66,77,55],[56,57,57]],
                      [[5,7,8],[33,22,11],[4,3,56]],
                      [[90,80,70],[34,35,36],[33,44,66]]],ndmin=10)
print(three_arr.ndim)
print(three_arr)
print(three_arr.shape)
print(three_arr.size)

10
[[[[[[[[[[ 4  5  6]
         [66 77 55]
         [56 57 57]]

        [[ 5  7  8]
         [33 22 11]
         [ 4  3 56]]

        [[90 80 70]
         [34 35 36]
         [33 44 66]]]]]]]]]]
(1, 1, 1, 1, 1, 1, 1, 3, 3, 3)
27


In [41]:
three_arr = np.array([[[4,5,6],[66,77,55],[56,57,57]],
                      [[5,7,8],[33,22,11],[4,3,56]],
                      [[90,80,70],[34,35,36],[33,44,66]]],ndmin=10,dtype=float)
print(three_arr.ndim)
print(three_arr)
print(three_arr.shape)
print(three_arr.size)

10
[[[[[[[[[[ 4.  5.  6.]
         [66. 77. 55.]
         [56. 57. 57.]]

        [[ 5.  7.  8.]
         [33. 22. 11.]
         [ 4.  3. 56.]]

        [[90. 80. 70.]
         [34. 35. 36.]
         [33. 44. 66.]]]]]]]]]]
(1, 1, 1, 1, 1, 1, 1, 3, 3, 3)
27


In [43]:
three_arr = np.array([[[4,5,6],[66,77,55],[56,57,57]],
                      [[5,7,8],[33,22,11],[4,3,56]],
                      [[90,80,70],[34,35,36],[33,44,66]]],ndmin=3,dtype=complex)
print(three_arr.ndim)
print(three_arr)
print(three_arr.shape)
print(three_arr.size)

3
[[[ 4.+0.j  5.+0.j  6.+0.j]
  [66.+0.j 77.+0.j 55.+0.j]
  [56.+0.j 57.+0.j 57.+0.j]]

 [[ 5.+0.j  7.+0.j  8.+0.j]
  [33.+0.j 22.+0.j 11.+0.j]
  [ 4.+0.j  3.+0.j 56.+0.j]]

 [[90.+0.j 80.+0.j 70.+0.j]
  [34.+0.j 35.+0.j 36.+0.j]
  [33.+0.j 44.+0.j 66.+0.j]]]
(3, 3, 3)
27


In [45]:
three_arr = np.array([[[4,5,6],[66,77,55],[56,57,57]],
                      [[5,7,8],[33,22,11],[4,3,56]],
                      [[90,80,70],[34,35,36],[33,44,66]]],ndmin=10,dtype=str)
print(three_arr.ndim)
print(three_arr)
print(three_arr.shape)
print(three_arr.size)
print(three_arr.dtype)

10
[[[[[[[[[['4' '5' '6']
         ['66' '77' '55']
         ['56' '57' '57']]

        [['5' '7' '8']
         ['33' '22' '11']
         ['4' '3' '56']]

        [['90' '80' '70']
         ['34' '35' '36']
         ['33' '44' '66']]]]]]]]]]
(1, 1, 1, 1, 1, 1, 1, 3, 3, 3)
27
<U2


In [47]:
# Zero array

py_arr = np.zeros((3,2))
print(py_arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [50]:
py_arr = np.zeros((3,3),dtype=int)
print(py_arr)
print(py_arr.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int64


In [ ]:
py_arr = np.zeros((3,3))
print(py_arr)

In [51]:
# ones

ones_array = np.ones((4,5))
print(ones_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
ones_array = np.ones((4,5),dtype=int)
print(ones_array)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Arange 

In [54]:
arrng = np.arange(9)
print(arrng)
print(arrng.ndim)

[0 1 2 3 4 5 6 7 8]
1


In [66]:
arrng = np.arange(9,15,)
print(arrng)
print(arrng.size)
print(arrng.ndim)
reshaped_arr = np.reshape(arrng,shape = (3,2))
print(reshaped_arr)

[ 9 10 11 12 13 14]
6
1
[[ 9 10]
 [11 12]
 [13 14]]


In [79]:
arrng = np.arange(7)
print(arrng)
print(arrng.ndim)
reshape_arr = np.reshape(arrng,shape = (7,1))
print(reshape_arr)
print(reshape_arr.ndim)

[0 1 2 3 4 5 6]
1
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]]
2


In [81]:
lin_spa = np.linspace(5,20,5)
print(lin_spa)

[ 5.    8.75 12.5  16.25 20.  ]


In [86]:
lin_spa = np.linspace(5,20,6)
print(lin_spa)
print(lin_spa.ndim)
reshap_lin = np.reshape(lin_spa,shape=(2,3))
print(reshap_lin)
print(reshap_lin.shape)

[ 5.  8. 11. 14. 17. 20.]
1
[[ 5.  8. 11.]
 [14. 17. 20.]]
(2, 3)


In [90]:
lin_spa = np.linspace(5,20,100)
print(lin_spa)
print(lin_spa.ndim)
print(lin_spa.size)
reshap_lin = np.reshape(lin_spa,shape=(20,5))
print(reshap_lin)
print(reshap_lin.shape)

[ 5.          5.15151515  5.3030303   5.45454545  5.60606061  5.75757576
  5.90909091  6.06060606  6.21212121  6.36363636  6.51515152  6.66666667
  6.81818182  6.96969697  7.12121212  7.27272727  7.42424242  7.57575758
  7.72727273  7.87878788  8.03030303  8.18181818  8.33333333  8.48484848
  8.63636364  8.78787879  8.93939394  9.09090909  9.24242424  9.39393939
  9.54545455  9.6969697   9.84848485 10.         10.15151515 10.3030303
 10.45454545 10.60606061 10.75757576 10.90909091 11.06060606 11.21212121
 11.36363636 11.51515152 11.66666667 11.81818182 11.96969697 12.12121212
 12.27272727 12.42424242 12.57575758 12.72727273 12.87878788 13.03030303
 13.18181818 13.33333333 13.48484848 13.63636364 13.78787879 13.93939394
 14.09090909 14.24242424 14.39393939 14.54545455 14.6969697  14.84848485
 15.         15.15151515 15.3030303  15.45454545 15.60606061 15.75757576
 15.90909091 16.06060606 16.21212121 16.36363636 16.51515152 16.66666667
 16.81818182 16.96969697 17.12121212 17.27272727 17.

In [91]:
log_spa = np.logspace(5,20,100)
print(log_spa)
print(log_spa.ndim)
print(log_spa.size)
reshap_log = np.reshape(log_spa,shape=(20,5))
print(reshap_log)
print(reshap_log.shape)

[1.00000000e+05 1.41747416e+05 2.00923300e+05 2.84803587e+05
 4.03701726e+05 5.72236766e+05 8.11130831e+05 1.14975700e+06
 1.62975083e+06 2.31012970e+06 3.27454916e+06 4.64158883e+06
 6.57933225e+06 9.32603347e+06 1.32194115e+07 1.87381742e+07
 2.65608778e+07 3.76493581e+07 5.33669923e+07 7.56463328e+07
 1.07226722e+08 1.51991108e+08 2.15443469e+08 3.05385551e+08
 4.32876128e+08 6.13590727e+08 8.69749003e+08 1.23284674e+09
 1.74752840e+09 2.47707636e+09 3.51119173e+09 4.97702356e+09
 7.05480231e+09 1.00000000e+10 1.41747416e+10 2.00923300e+10
 2.84803587e+10 4.03701726e+10 5.72236766e+10 8.11130831e+10
 1.14975700e+11 1.62975083e+11 2.31012970e+11 3.27454916e+11
 4.64158883e+11 6.57933225e+11 9.32603347e+11 1.32194115e+12
 1.87381742e+12 2.65608778e+12 3.76493581e+12 5.33669923e+12
 7.56463328e+12 1.07226722e+13 1.51991108e+13 2.15443469e+13
 3.05385551e+13 4.32876128e+13 6.13590727e+13 8.69749003e+13
 1.23284674e+14 1.74752840e+14 2.47707636e+14 3.51119173e+14
 4.97702356e+14 7.054802

# Mathematical operation in numpy

In [93]:
a = np.array([[3,5],[7,8]])
b = np.array([[8,2],[9,10]])
print(a)
print(b)
Sum = a + b
print(Sum)

[[3 5]
 [7 8]]
[[ 8  2]
 [ 9 10]]
[[11  7]
 [16 18]]


In [94]:
addition = np.add(a,b)
print(addition)

[[11  7]
 [16 18]]


In [99]:
a = np.array([[[3,5],[7,8]],[[8,2],[9,10]]])
b = np.array([[[8,2],[9,10]],[[3,5],[7,8]]])
print(a)
print(b)
print(a.shape,b.shape)

[[[ 3  5]
  [ 7  8]]

 [[ 8  2]
  [ 9 10]]]
[[[ 8  2]
  [ 9 10]]

 [[ 3  5]
  [ 7  8]]]
(2, 2, 2) (2, 2, 2)


In [ ]:
Add_3d = np.add(a,b)
print(Add_3d)

[[[11  7]
  [16 18]]

 [[11  7]
  [16 18]]]


In [101]:
# substraction 
a = np.array([[3,5],[7,8]])
b = np.array([[8,2],[9,10]])

print(a-b)

[[-5  3]
 [-2 -2]]


In [102]:
a = np.array([[3,5],[7,8]])
b = np.array([[8,2],[9,10]])

Sub_2d = np.subtract(a,b)
print(Sub_2d)

[[-5  3]
 [-2 -2]]


In [103]:
a = np.array([[[3,5],[7,8]],[[8,2],[9,10]]])
b = np.array([[[8,2],[9,10]],[[3,5],[7,8]]])
print(a)
print(b)
print(a.shape,b.shape)
print(a-b)

[[[ 3  5]
  [ 7  8]]

 [[ 8  2]
  [ 9 10]]]
[[[ 8  2]
  [ 9 10]]

 [[ 3  5]
  [ 7  8]]]
(2, 2, 2) (2, 2, 2)
[[[-5  3]
  [-2 -2]]

 [[ 5 -3]
  [ 2  2]]]


In [ ]:
a = np.array([[[3,5],[7,8]],[[8,2],[9,10]]])
b = np.array([[[8,2],[9,10]],[[3,5],[7,8]]])
print(a)
print("--"*50)
print(b)
print(a.shape,b.shape)
Sub_3d = np.subtract(a,b)
print("--"*50)
print(Sub_3d) 

[[[ 3  5]
  [ 7  8]]

 [[ 8  2]
  [ 9 10]]]
----------------------------------------------------------------------------------------------------
[[[ 8  2]
  [ 9 10]]

 [[ 3  5]
  [ 7  8]]]
(2, 2, 2) (2, 2, 2)
----------------------------------------------------------------------------------------------------
[[[-5  3]
  [-2 -2]]

 [[ 5 -3]
  [ 2  2]]]
